dist: xenial
language: python
services:
    - docker
python:
    - "3.7"
install:
    - pip install -r requirements.txt
# Docker release
deploy:
    - skip_cleanup: true
      provider: script
      script: python ./deploy.py
      on:
          branch: master
          tags: true
