dist: xenial
language: python
services:
    - docker
python:
    - "3.7"
# Docker release
deploy:
    - skip_cleanup: true
      provider: script
      script: python ./deploy.py
      on:
          branch: master
          tags: true
