dist: bionic
language: minimal
services:
    - docker
script:
    - echo Success
# Docker release
deploy:
    - skip_cleanup: true
      provider: script
      script: ./build.sh
      on:
          branch: master
          tags: true
