name: Build and Publish Images
on:
    release:
        types: [released, prereleased]
jobs:
    build-and-publish:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - run: chmod +x ./build.sh && ./build.sh
              env:
                  DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
                  DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
